name: Deploy to GCP VM

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: DAMG7250 	
  GCP_VM_INSTANCE_NAME: damg7250-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: SSH into GCP VM Compute
        uses: appleboy/ssh-action@master
        with:
          SSH_DEBUG: true
          host: 34.138.242.155
          username: snehil_aryan7823
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      - name: Run Docker container
        run: |
          sudo docker ps
